Marts: ; 160a9
	dw Mart0  ; MART_CHERRYGROVE
	dw Mart1  ; MART_CHERRYGROVE_DEX
	dw Mart2  ; MART_VIOLET
	dw Mart3  ; MART_AZALEA
	dw Mart4  ; MART_CIANWOOD
	dw Mart5  ; MART_GOLDENROD_2F_1
	dw Mart6  ; MART_GOLDENROD_2F_2
	dw Mart7  ; MART_GOLDENROD_3F
	dw Mart8  ; MART_GOLDENROD_4F
	dw Mart9  ; MART_GOLDENROD_5F_1
	dw Mart10 ; MART_GOLDENROD_5F_2
	dw Mart11 ; MART_GOLDENROD_5F_3
	dw Mart12 ; MART_GOLDENROD_5F_4
	dw Mart13 ; MART_OLIVINE
	dw Mart14 ; MART_ECRUTEAK
	dw Mart15 ; MART_MAHOGANY_1
	dw Mart16 ; MART_MAHOGANY_2
	dw Mart17 ; MART_BLACKTHORN
	dw Mart18 ; MART_VIRIDIAN
	dw Mart19 ; MART_PEWTER
	dw Mart20 ; MART_CERULEAN
	dw Mart21 ; MART_LAVENDER
	dw Mart22 ; MART_VERMILION
	dw Mart23 ; MART_CELADON_2F_1
	dw Mart24 ; MART_CELADON_2F_2
	dw Mart25 ; MART_CELADON_3F
	dw Mart26 ; MART_CELADON_4F
	dw Mart27 ; MART_CELADON_5F_1
	dw Mart28 ; MART_CELADON_5F_2
	dw Mart29 ; MART_FUCHSIA
	dw Mart30 ; MART_SAFFRON
	dw Mart31 ; MART_MT_MOON
	dw Mart32 ; MART_INDIGO_PLATEAU
	dw Mart33 ; MART_UNDERGROUND
MartsEnd
; 160ed


Mart0: ; 160ed - MART_CHERRYGROVE
	db 4 ; # items
	db POTION
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db $ff
; 160f3

Mart1: ; 160f3 - MART_CHERRYGROVE_DEX
	db 5 ; # items
	db POKE_BALL
	db POTION
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db $ff
; 160fa

Mart2: ; 160fa - MART_VIOLET
	db 10 ; # items
	db POKE_BALL
	db POTION
	db ESCAPE_ROPE
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db X_DEFEND
	db X_ATTACK
	db X_SPEED
	db FLOWER_MAIL
	db $ff
; 16106

Mart3: ; 16106 - MART_AZALEA
	db 9 ; # items
	db CHARCOAL
	db POKE_BALL
	db POTION
	db SUPER_POTION
	db ESCAPE_ROPE
	db REPEL
	db ANTIDOTE
	db PARLYZ_HEAL
	db FLOWER_MAIL
	db $ff
; 16111

Mart4: ; 16111 - MART_CIANWOOD
	db 5 ; # items
	db POTION
	db SUPER_POTION
	db HYPER_POTION
	db FULL_HEAL
	db REVIVE
	db $ff
; 16118

Mart5: ; 16118 - GOLDENROD_2F_1
	db 7 ; # items
	db POTION
	db SUPER_POTION
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db BURN_HEAL
	db ICE_HEAL
	db $ff
; 16121

Mart6: ; 16121 - GOLDENROD_2F_2
	db 9 ; # items
	db POKE_BALL
	db GREAT_BALL
	db ESCAPE_ROPE
	db REPEL
	db REVIVE
	db FULL_HEAL
	db POKE_DOLL
	db FLOWER_MAIL
	db LINK_CABLE
	db $ff
; 1612b

Mart7: ; 1612b - MART_GOLDENROD_3F
	db 7 ; # items
	db X_SPEED
	db X_SPECIAL
	db X_DEFEND
	db X_ATTACK
	db DIRE_HIT
	db GUARD_SPEC
	db X_ACCURACY
	db $ff
; 16134

Mart8: ; 16134 - MART_GOLDENROD_4F
	db 6 ; # items
	db PROTEIN
	db IRON
	db CARBOS
	db CALCIUM
	db HP_UP
	db PP_UP
	db $ff
; 1613b

Mart9: ; 1613b - MART_GOLDENROD_5F_1
	db 3 ; # items
	db TM_THUNDERPUNCH
	db TM_FIRE_PUNCH
	db TM_ICE_PUNCH
	db $ff
; 16140

Mart10: ; 16140 - MART_GOLDENROD_5F_2
	db 4 ; # items
	db TM_THUNDERPUNCH
	db TM_FIRE_PUNCH
	db TM_ICE_PUNCH
	db TM_HEADBUTT
	db $ff
; 16146

Mart11: ; 16146 - MART_GOLDENROD_5F_3
	db 4 ; # items
	db TM_THUNDERPUNCH
	db TM_FIRE_PUNCH
	db TM_ICE_PUNCH
	db TM_ROCK_SMASH
	db $ff
; 1614c

Mart12: ; 1614c - MART_GOLDENROD_5F_4
	db 5 ; # items
	db TM_THUNDERPUNCH
	db TM_FIRE_PUNCH
	db TM_ICE_PUNCH
	db TM_HEADBUTT
	db TM_ROCK_SMASH
	db $ff
; 16153

Mart13: ; 16153 - MART_OLIVINE
	db 9 ; # items
	db GREAT_BALL
	db SUPER_POTION
	db HYPER_POTION
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db ICE_HEAL
	db SUPER_REPEL
	db SURF_MAIL
	db $ff
; 1615e

Mart14: ; 1615e - MART_ECRUTEAK
	db 10 ; # items
	db POKE_BALL
	db GREAT_BALL
	db POTION
	db SUPER_POTION
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db BURN_HEAL
	db ICE_HEAL
	db REVIVE
	db $ff
; 1616a

Mart15: ; 1616a - MART_MAHOGANY_1
	db 4 ; # items
	db TINYMUSHROOM
	db SLOWPOKETAIL
	db POKE_BALL
	db POTION
	db $ff
; 16170

Mart16: ; 16170 - MART_MAHOGANY_2
	db 9 ; # items
	db RAGECANDYBAR
	db GREAT_BALL
	db SUPER_POTION
	db HYPER_POTION
	db ANTIDOTE
	db PARLYZ_HEAL
	db SUPER_REPEL
	db REVIVE
	db FLOWER_MAIL
	db $ff
; 1617b

Mart17: ; 1617b - MART_BLACKTHORN
	db 9 ; # items
	db GREAT_BALL
	db ULTRA_BALL
	db HYPER_POTION
	db MAX_POTION
	db FULL_HEAL
	db REVIVE
	db MAX_REPEL
	db X_DEFEND
	db X_ATTACK
	db $ff
; 16186

Mart18: ; 16186 - MART_VIRIDIAN
	db 9 ; # items
	db ULTRA_BALL
	db HYPER_POTION
	db FULL_HEAL
	db REVIVE
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db BURN_HEAL
	db FLOWER_MAIL
	db $ff
; 16191

Mart19: ; 16191 - MART_PEWTER
	db 7 ; # items
	db GREAT_BALL
	db SUPER_POTION
	db SUPER_REPEL
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db BURN_HEAL
	db $ff
; 1619a

Mart20: ; 1619a - MART_CERULEAN
	db 9 ; # items
	db GREAT_BALL
	db ULTRA_BALL
	db SUPER_POTION
	db SUPER_REPEL
	db FULL_HEAL
	db X_DEFEND
	db X_ATTACK
	db DIRE_HIT
	db SURF_MAIL
	db $ff
; 161a5

Mart21: ; 161a5 - MART_LAVENDER
	db 8 ; # items
	db GREAT_BALL
	db POTION
	db SUPER_POTION
	db MAX_REPEL
	db ANTIDOTE
	db PARLYZ_HEAL
	db AWAKENING
	db BURN_HEAL
	db $ff
; 161af

Mart22: ; 161af - MART_VERMILION
	db 8 ; # items
	db ULTRA_BALL
	db SUPER_POTION
	db HYPER_POTION
	db REVIVE
	db PARLYZ_HEAL
	db AWAKENING
	db BURN_HEAL
	db LITEBLUEMAIL
	db $ff
; 161b9

Mart23: ; 161b9 - MART_CELADON_2F_1
	db 7 ; # items
	db POTION
	db SUPER_POTION
	db HYPER_POTION
	db MAX_POTION
	db REVIVE
	db SUPER_REPEL
	db MAX_REPEL
	db $ff
; 161c2

Mart24: ; 161c2 - MART_CELADON_2F_2
	db 10 ; # items
	db POKE_BALL
	db GREAT_BALL
	db ULTRA_BALL
	db ESCAPE_ROPE
	db FULL_HEAL
	db ANTIDOTE
	db BURN_HEAL
	db ICE_HEAL
	db AWAKENING
	db PARLYZ_HEAL
	db $ff
; 161ce

Mart25: ; 161ce - MART_CELADON_3F
	db 5 ; # items
	db TM_HIDDEN_POWER
	db TM_SUNNY_DAY
	db TM_PROTECT
	db TM_RAIN_DANCE
	db TM_SANDSTORM
	db $ff
; 161d5

Mart26: ; 161d5 - MART_CELADON_4F
	db 10 ; # items
	db POKE_DOLL
	db LOVELY_MAIL
	db SURF_MAIL
	db FIRE_STONE
	db WATER_STONE
	db THUNDERSTONE
	db LEAF_STONE
	db MOON_STONE
	db SUN_STONE
	db LINK_CABLE
	db $ff
; 161da

Mart27: ; 161da - MART_CELADON_5F_1
	db 6 ; # items
	db HP_UP
	db PROTEIN
	db IRON
	db CARBOS
	db CALCIUM
	db PP_UP
	db $ff
; 161e1

Mart28: ; 161e1 - MART_CELADON_5F_2
	db 7 ; # items
	db X_ACCURACY
	db GUARD_SPEC
	db DIRE_HIT
	db X_ATTACK
	db X_DEFEND
	db X_SPEED
	db X_SPECIAL
	db $ff
; 161ea

Mart29: ; 161ea - MART_FUCHSIA
	db 7 ; # items
	db GREAT_BALL
	db ULTRA_BALL
	db SUPER_POTION
	db HYPER_POTION
	db FULL_HEAL
	db MAX_REPEL
	db FLOWER_MAIL
	db $ff
; 161f3

Mart30: ; 161f3 - MART_SAFFRON
	db 7 ; # items
	db GREAT_BALL
	db ULTRA_BALL
	db HYPER_POTION
	db MAX_POTION
	db FULL_HEAL
	db X_ATTACK
	db X_DEFEND
	db $ff
; 161fd

Mart31: ; 161fd - MART_MT_MOON
	db 6 ; # items
	db POKE_DOLL
	db FRESH_WATER
	db SODA_POP
	db LEMONADE
	db REPEL
	db PORTRAITMAIL
	db $ff
; 16205

Mart32: ; 16205 - MART_INDIGO_PLATEAU
	db 7 ; # items
	db ULTRA_BALL
	db MAX_REPEL
	db HYPER_POTION
	db MAX_POTION
	db FULL_RESTORE
	db REVIVE
	db FULL_HEAL
	db $ff
; 1620e

Mart33: ; 1620e - MART_UNDERGROUND
	db 4 ; # items
	db ENERGYPOWDER
	db ENERGY_ROOT
	db HEAL_POWDER
	db REVIVAL_HERB
	db $ff
; 16214

DefaultMart: ; 16214
	db 2 ; # items
	db POKE_BALL
	db POTION
	db $ff
; 16218
